echo -n stop | openssl sha1
echo -n zzzzx | openssl sha1
echo -n trip | openssl sha1
echo -n aaaa | openssl sha1
echo -n zzzzz | openssl sha1
echo -n fuck | openssl sha1
echo -n mens | openssl sha1
echo -n asdf | openssl sha1
echo -n hipr | openssl sha1
echo -n ksjdnfkjsdnf | openssl sha1
