/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _LSP_RPC_H_RPCGEN
#define _LSP_RPC_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct LSPMessage1 {
	int connid;
	int seqnum;
	char *payload;
};
typedef struct LSPMessage1 LSPMessage1;

#define LSP_PROGRAM 0x37987898
#define LSP_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define sendfn 1
extern  int * sendfn_1(LSPMessage1 *, CLIENT *);
extern  int * sendfn_1_svc(LSPMessage1 *, struct svc_req *);
#define recvfn 2
extern  LSPMessage1 * recvfn_1(int *, CLIENT *);
extern  LSPMessage1 * recvfn_1_svc(int *, struct svc_req *);
extern int lsp_program_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define sendfn 1
extern  int * sendfn_1();
extern  int * sendfn_1_svc();
#define recvfn 2
extern  LSPMessage1 * recvfn_1();
extern  LSPMessage1 * recvfn_1_svc();
extern int lsp_program_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_LSPMessage1 (XDR *, LSPMessage1*);

#else /* K&R C */
extern bool_t xdr_LSPMessage1 ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_LSP_RPC_H_RPCGEN */
