/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "lsp_rpc.h"

bool_t
xdr_LSPMessage1 (XDR *xdrs, LSPMessage1 *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->connid))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->seqnum))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->payload, 1000))
		 return FALSE;
	return TRUE;
}
